---
- name: Ensure the command completes successfully
  ansible.builtin.shell: oc get co
  register: result
  retries: 5
  delay: 60
  until: result.rc == 0
  ignore_errors: true

- name: Create etcd-guard Deployment
  community.okd.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: etcd-guard-control-plane-cluster-1
        namespace: openshift-etcd
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: etcd
        template:
          metadata:
            labels:
              app: etcd
          spec:
            containers:
            - name: etcd-guard
              image: quay.io/mpeterma/rh1_ctf/rh1-etcd-guard:latest