---
- name: Deploy triwizard-tournament ConfigMap in openshift-etcd
  community.okd.k8s:
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: triwizard-tournament
        namespace: openshift-etcd
      data:
        hogwarts: |
          FnZT1xdWF5LmlvL21wZXRlcm1hL3JoMV
        durmstrang: |
          b2MgcnVuIHRyaXdpemFyZC1jdXAgLS1pbW
        beauxbatons: |
          9jdGYvcmgxLXRyaXdpemFyZC1jdXA6djEK
        README.md: |
          'Alone they can't win, together they can?'
  register: result
  retries: 10
  delay: 60
  until: result is successful